# Generated by Django 4.2.3 on 2024-07-14 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iid', models.IntegerField(default=-1, verbose_name='规则编号')),
                ('pid', models.CharField(default='P00', max_length=10, verbose_name='参与者')),
                ('rule', models.CharField(default='', max_length=100, verbose_name='规则')),
                ('isactivate', models.BooleanField(default=True, verbose_name='激活')),
                ('platform', models.CharField(choices=[('B站', 'B站'), ('知乎', '知乎'), ('小红书', '小红书'), ('微博', '微博')], default='知乎', max_length=10, verbose_name='平台')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(default='P00', max_length=10, verbose_name='参与者')),
                ('task', models.CharField(choices=[], default='无', max_length=100, verbose_name='任务')),
                ('platform', models.CharField(choices=[('B站', 'B站'), ('知乎', '知乎'), ('小红书', '小红书'), ('微博', '微博')], default='知乎', max_length=10, verbose_name='平台')),
                ('summary', models.CharField(default='', max_length=100, verbose_name='总结')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(default='', max_length=10, verbose_name='参与者')),
                ('platform', models.CharField(choices=[('B站', 'B站'), ('知乎', '知乎'), ('小红书', '小红书'), ('微博', '微博')], default='知乎', max_length=10, verbose_name='平台')),
                ('title', models.CharField(default='', max_length=200, verbose_name='标题')),
                ('content', models.CharField(default='', max_length=1000, verbose_name='内容')),
                ('url', models.CharField(default='', max_length=1000, verbose_name='网址')),
                ('click', models.BooleanField(default=False, verbose_name='点击')),
                ('browse_time', models.DateTimeField(auto_now_add=True, verbose_name='浏览时间')),
                ('click_time', models.DateTimeField(auto_now=True, verbose_name='交互时间')),
                ('context', models.CharField(default='', max_length=1000, verbose_name='上下文')),
                ('is_filter', models.BooleanField(default=True, verbose_name='开关')),
                ('filter_result', models.BooleanField(default=True, verbose_name='屏蔽')),
                ('filter_reason', models.CharField(default='', max_length=1000, verbose_name='原因')),
            ],
            options={
                'verbose_name': '记录',
                'verbose_name_plural': '记录',
                'indexes': [models.Index(fields=['pid'], name='agent_recor_pid_a3c658_idx'), models.Index(fields=['platform'], name='agent_recor_platfor_59f295_idx'), models.Index(fields=['pid', 'platform'], name='agent_recor_pid_9e2e06_idx'), models.Index(fields=['pid', 'platform', 'title'], name='agent_recor_pid_34dbc5_idx')],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('sender', models.CharField(choices=[('user', 'user'), ('assistant', 'assistant'), ('bot', 'bot')], default='bot', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.session')),
            ],
        ),
        migrations.CreateModel(
            name='Chilog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(default='P00', max_length=10, verbose_name='参与者')),
                ('botadd', models.BooleanField(default=False, verbose_name='是否bot添加')),
                ('botchange', models.BooleanField(default=False, verbose_name='是否bot更新')),
                ('iid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.rule')),
            ],
        ),
    ]
