# Generated by Django 4.2.3 on 2024-07-14 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rule',
            old_name='isactivate',
            new_name='isactive',
        ),
    ]
