# Generated by Django 4.2.3 on 2024-07-15 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_rename_isactivate_rule_isactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='platform',
            field=models.CharField(choices=[('知乎', '知乎'), ('B站', 'B站'), ('小红书', '小红书'), ('微博', '微博')], default='知乎', max_length=10, verbose_name='平台'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='platform',
            field=models.CharField(choices=[('知乎', '知乎'), ('B站', 'B站'), ('小红书', '小红书'), ('微博', '微博')], default='知乎', max_length=10, verbose_name='平台'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='rule',
            field=models.CharField(choices=[('0', '变更画像'), ('1', '对齐画像'), ('2', '查看留痕')], default='0', max_length=100, verbose_name='规则'),
        ),
        migrations.AlterField(
            model_name='session',
            name='platform',
            field=models.CharField(choices=[('知乎', '知乎'), ('B站', 'B站'), ('小红书', '小红书'), ('微博', '微博')], default='知乎', max_length=10, verbose_name='平台'),
        ),
        migrations.CreateModel(
            name='Searchlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(default='P00', max_length=10, verbose_name='参与者')),
                ('platform', models.CharField(choices=[('知乎', '知乎'), ('B站', 'B站'), ('小红书', '小红书'), ('微博', '微博')], default='知乎', max_length=10, verbose_name='平台')),
                ('keyword', models.CharField(default='', max_length=100, verbose_name='关键词')),
                ('task', models.CharField(choices=[('0', '变更画像'), ('1', '对齐画像'), ('2', '查看留痕')], default='0', max_length=100, verbose_name='任务')),
                ('is_accepted', models.BooleanField(default=False, verbose_name='是否被接受')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('iitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.rule')),
            ],
        ),
    ]
