# Generated by Django 4.2.3 on 2024-07-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_alter_record_platform_alter_rule_platform_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personalities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(default='P00', max_length=10, verbose_name='参与者')),
                ('platform', models.CharField(choices=[('知乎', '知乎'), ('B站', 'B站'), ('小红书', '小红书'), ('微博', '微博')], default='知乎', max_length=10, verbose_name='平台')),
                ('personality', models.CharField(default='', max_length=100, verbose_name='个性化偏好')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
    ]
