# Generated by Django 4.2.3 on 2024-07-18 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0004_personalities'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalities',
            name='first_response',
            field=models.CharField(default='', max_length=500, verbose_name='第一句回答'),
        ),
        migrations.AlterField(
            model_name='personalities',
            name='personality',
            field=models.CharField(default='', max_length=500, verbose_name='个性化偏好'),
        ),
    ]
