# Generated by Django 4.2.3 on 2024-07-18 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0005_personalities_first_response_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchlog',
            name='iitem',
        ),
    ]
