# Generated by Django 4.2.3 on 2024-07-18 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0006_remove_searchlog_iitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchlog',
            name='task',
        ),
    ]
