# Generated by Django 4.2.3 on 2024-07-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0007_remove_searchlog_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='has_action',
            field=models.BooleanField(default=False),
        ),
    ]
