# Generated by Django 4.2.3 on 2024-07-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0009_remove_message_has_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='has_action',
            field=models.BooleanField(default=False),
        ),
    ]
