# Generated by Django 4.2.3 on 2024-07-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0010_message_has_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalities',
            name='personality_click',
            field=models.CharField(default='', max_length=500, verbose_name='点击偏好'),
        ),
    ]
