# Generated by Django 4.2.3 on 2024-07-21 09:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0011_personalities_personality_click'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenContentlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(default='P00', max_length=10, verbose_name='参与者')),
                ('action_type', models.CharField(choices=[('add', 'add'), ('update', 'update'), ('delete', 'delete')], default='add', max_length=10)),
                ('platform', models.CharField(choices=[('知乎', '知乎'), ('B站', 'B站'), ('小红书', '小红书'), ('微博', '微博')], default='知乎', max_length=10, verbose_name='平台')),
                ('new_rule', models.CharField(max_length=100, verbose_name='生成规则')),
                ('old_rule', models.CharField(max_length=100, verbose_name='原规则')),
                ('is_ac', models.BooleanField(default=True, verbose_name='是否被接受')),
                ('change_rule', models.CharField(max_length=100, verbose_name='用户编辑后的规则')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
            ],
        ),
        migrations.RenameField(
            model_name='searchlog',
            old_name='keyword',
            new_name='gen_keyword',
        ),
        migrations.RemoveField(
            model_name='chilog',
            name='botadd',
        ),
        migrations.RemoveField(
            model_name='chilog',
            name='botchange',
        ),
        migrations.AddField(
            model_name='chilog',
            name='action_type',
            field=models.CharField(choices=[('add', 'add'), ('update', 'update'), ('delete', 'delete')], default='add', max_length=10),
        ),
        migrations.AddField(
            model_name='chilog',
            name='isactive',
            field=models.BooleanField(default=True, null=True, verbose_name='改变后的激活'),
        ),
        migrations.AddField(
            model_name='chilog',
            name='isbot',
            field=models.BooleanField(default=False, verbose_name='是否是通过bot操作'),
        ),
        migrations.AddField(
            model_name='chilog',
            name='platform',
            field=models.CharField(choices=[('知乎', '知乎'), ('B站', 'B站'), ('小红书', '小红书'), ('微博', '微博')], default='知乎', max_length=10, null=True, verbose_name='改变后的平台'),
        ),
        migrations.AddField(
            model_name='chilog',
            name='rule',
            field=models.CharField(max_length=100, null=True, verbose_name='改变后的规则'),
        ),
        migrations.AddField(
            model_name='chilog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='searchlog',
            name='edited_keyword',
            field=models.CharField(default='', max_length=100, verbose_name='用户编辑后的关键词'),
        ),
        migrations.AlterField(
            model_name='chilog',
            name='iid',
            field=models.IntegerField(default=-1, verbose_name='规则编号'),
        ),
    ]
