# Generated by Django 4.2.3 on 2024-07-22 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent", "0012_gencontentlog_rename_keyword_searchlog_gen_keyword_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="sum_content",
            field=models.CharField(default="", max_length=1000, verbose_name="摘要"),
        ),
    ]
