# Generated by Django 4.1 on 2024-08-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0016_alter_rule_rule"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chilog",
            options={"verbose_name": "规则编辑日志", "verbose_name_plural": "规则编辑日志"},
        ),
        migrations.AlterModelOptions(
            name="gencontentlog",
            options={"verbose_name": "规则生成日志", "verbose_name_plural": "规则生成日志"},
        ),
        migrations.AlterModelOptions(
            name="message",
            options={"verbose_name": "消息", "verbose_name_plural": "消息"},
        ),
        migrations.AlterModelOptions(
            name="personalities",
            options={"verbose_name": "个性化偏好", "verbose_name_plural": "个性化偏好"},
        ),
        migrations.AlterModelOptions(
            name="personalitiesclick",
            options={"verbose_name": "RAH生成的点击偏好", "verbose_name_plural": "RAH生成的点击偏好"},
        ),
        migrations.AlterModelOptions(
            name="rule",
            options={"verbose_name": "规则", "verbose_name_plural": "规则"},
        ),
        migrations.AlterModelOptions(
            name="searchlog",
            options={"verbose_name": "搜索日志", "verbose_name_plural": "搜索日志"},
        ),
        migrations.AlterModelOptions(
            name="session",
            options={"verbose_name": "会话", "verbose_name_plural": "会话"},
        ),
        migrations.AlterField(
            model_name="chilog",
            name="action_type",
            field=models.CharField(
                choices=[("add", "add"), ("update", "update"), ("delete", "delete")],
                default="add",
                max_length=10,
                verbose_name="操作类型",
            ),
        ),
        migrations.AlterField(
            model_name="gencontentlog",
            name="action_type",
            field=models.CharField(
                choices=[("add", "add"), ("update", "update"), ("delete", "delete")],
                default="add",
                max_length=10,
                verbose_name="操作类型",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="content",
            field=models.CharField(max_length=255, verbose_name="内容"),
        ),
        migrations.AlterField(
            model_name="message",
            name="sender",
            field=models.CharField(
                choices=[("user", "user"), ("assistant", "assistant"), ("bot", "bot")],
                default="bot",
                max_length=10,
                verbose_name="发送者",
            ),
        ),
        migrations.AlterField(
            model_name="record",
            name="context",
            field=models.CharField(default="", max_length=1000, verbose_name="对应规则"),
        ),
        migrations.AlterField(
            model_name="record",
            name="filter_result",
            field=models.BooleanField(default=False, verbose_name="屏蔽"),
        ),
        migrations.AddIndex(
            model_name="rule",
            index=models.Index(fields=["pid"], name="agent_rule_pid_44b9df_idx"),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(fields=["pid"], name="agent_sessi_pid_b55e2a_idx"),
        ),
    ]
