# Generated by Django 4.1 on 2024-08-04 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0019_remove_chilog_from_which_session_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gencontentlog",
            name="from_which_message",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="agent.message",
            ),
        ),
    ]
