# Generated by Django 5.2.10 on 2026-01-12 07:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0020_gencontentlog_from_which_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="filter_reason",
            field=models.CharField(default="", max_length=2000, verbose_name="原因"),
        ),
    ]
