# Generated by Django 5.2.12 on 2026-04-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0021_alter_record_filter_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chilog',
            name='platform',
            field=models.CharField(choices=[('知乎', '知乎'), ('B站', 'B站'), ('头条', '头条')], default='知乎', max_length=10, null=True, verbose_name='改变后的平台'),
        ),
        migrations.AlterField(
            model_name='gencontentlog',
            name='platform',
            field=models.CharField(choices=[('知乎', '知乎'), ('B站', 'B站'), ('头条', '头条')], default='知乎', max_length=10, verbose_name='平台'),
        ),
        migrations.AlterField(
            model_name='personalities',
            name='platform',
            field=models.CharField(choices=[('知乎', '知乎'), ('B站', 'B站'), ('头条', '头条')], default='知乎', max_length=10, verbose_name='平台'),
        ),
        migrations.AlterField(
            model_name='personalitiesclick',
            name='platform',
            field=models.CharField(choices=[('知乎', '知乎'), ('B站', 'B站'), ('头条', '头条')], default='知乎', max_length=10, verbose_name='平台'),
        ),
        migrations.AlterField(
            model_name='record',
            name='platform',
            field=models.CharField(choices=[('知乎', '知乎'), ('B站', 'B站'), ('头条', '头条')], default='知乎', max_length=10, verbose_name='平台'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='platform',
            field=models.CharField(choices=[('知乎', '知乎'), ('B站', 'B站'), ('头条', '头条')], default='知乎', max_length=10, verbose_name='平台'),
        ),
        migrations.AlterField(
            model_name='searchlog',
            name='platform',
            field=models.CharField(choices=[('知乎', '知乎'), ('B站', 'B站'), ('头条', '头条')], default='知乎', max_length=10, verbose_name='平台'),
        ),
        migrations.AlterField(
            model_name='session',
            name='platform',
            field=models.CharField(choices=[('知乎', '知乎'), ('B站', 'B站'), ('头条', '头条')], default='知乎', max_length=10, verbose_name='平台'),
        ),
    ]
