# Generated by Django 5.2.12 on 2026-04-11 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0023_alter_chilog_platform_alter_gencontentlog_platform_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReorderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=10, verbose_name='参与者')),
                ('platform', models.CharField(choices=[('头条', '头条'), ('知乎', '知乎'), ('B站', 'B站')], max_length=10, verbose_name='平台')),
                ('input_items', models.TextField(verbose_name='输入列表')),
                ('output_order', models.TextField(verbose_name='输出顺序')),
                ('removed_items', models.TextField(default='[]', verbose_name='移除列表')),
                ('positive_rules', models.TextField(default='', verbose_name='正向规则')),
                ('negative_rules', models.TextField(default='', verbose_name='负向规则')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
            ],
            options={
                'verbose_name': '重排日志',
                'verbose_name_plural': '重排日志',
            },
        ),
    ]
